const NOSTR_KINDS = {
  INVITE: 1111,
  MESSAGE: 1112,
  RESPONSE: 1113
};

const EVENT_TYPES = {
  INVITE: 'INVITE',
  MESSAGE: 'MESSAGE',
  RESPONSE: 'RESPONSE'
};

const RESPONSE_STATUS = {
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING'
};

module.exports = {
  NOSTR_KINDS,
  EVENT_TYPES,
  RESPONSE_STATUS
}; 